// BSDF Declarations
#pragma  once

enum BXDFType {
    BSDF_REFLECTION = 1U << 0,
    BSDF_TRANSMISSION = 1U << 1,
    BSDF_DIFFUSE = 1U << 2,
    BSDF_GLOSSY = 1U << 3,
    BSDF_SPECULAR = 1U << 4,
    BSDF_FORWARD = 1U<<5,
    BSDF_ALL = BSDF_DIFFUSE | BSDF_GLOSSY | BSDF_SPECULAR | BSDF_REFLECTION |
               BSDF_TRANSMISSION,
    BSDF_NO_SPECULAR = ~ (BSDF_SPECULAR | BSDF_FORWARD),
  //  BSDF_NO_SPECULAR = BSDF_DIFFUSE | BSDF_GLOSSY,
    BSDF_PURE_SPECULR = BSDF_SPECULAR | BSDF_TRANSMISSION | BSDF_REFLECTION
};

inline bool isSpecualr(BXDFType type){
    return BXDFType(type &  BSDF_SPECULAR) ==  BSDF_SPECULAR;
}